---
output:
  html_document:
runtime: shiny
---
Please ensure that your data follows a comma-separated (`CSV`) format. We assume 
that the dataset includes the following columns:

- **`ID`**: This column should contain the subject's ID, which can be either 
characters or numerical values.
- **`Day\Week`**: This column should represent the number of days or weeks using 
integers.
- **`Beep`**: Here, integers should indicate the number of beeps, arranged in 
ascending order.
- **`Autoregressive`**: Choose mood observations for these columns, ideally 
mean-centered for each subject. These selections should represent the 
interacting moods within the network depiction.
- **`Exogenous`**: These columns should encompass external factors, functioning 
as nodes that concurrently impact all AR nodes.

You will need to select the appropriate columns from the provided drop-down 
menus. If you desire shorter variable names, you have the option to specify the 
desired number of characters in the **Abbreviation** menu. Selecting **0** will 
result in no abbreviations being applied.

Once you've designated all the necessary variables, the default model formula 
will be established in the subsequent **Model** panel.






