---
output:
  html_document:
runtime: shiny
---
Upon importing your data and selecting the relevant variables, an **lmer** 
formula will emerge within the **Formula** section. This model operates under 
the assumption of a fully connected mood network, where all autoregressive (AR) 
and exogenous (EX) variables encompass both fixed and random components.

### Adding or Removing Fixed and Random Components
Each term within the "formula" adheres to the format "FROM_TO," denoting a 
temporal relation from the "FROM" variable to the "TO" variable, consequently 
establishing an edge in the network representation. The inclusion of terms in 
the formula is governed by an adjacency matrix that reflects the network 
structure. The presence of an edge is denoted by **1** in the cell located at 
the intersection of the column **FROM =>** and the row **=> TO**. If you wish to 
eliminate a specific term, modify the cell value to **0**. The upper and lower 
matrices correspond to fixed and random effects, respectively.


### Fitting the Data
By default, the outcomes are compressed into a zip file named 
"res_[date]_[time]", where date and time correspond to the moment when the 
**FIT** button was activated. If desired, you can opt to select an alternative 
destination for storing the results upon receiving a prompt following the 
completion of the fitting process.
- **`Save to`**: By default, the results will be stored in the user's "home" 
directory. A new folder named "res_[date]_[time]" will be created, with data 
and time values captured at the moment the FIT button is pressed. If desired, 
the root directory can be modified by selecting an alternative location 
using the "Save to" button.
- **`IDs to Fit`**: In this section, you have the option to select one or 
multiple subject IDs for the fitting process. Opting for **All** will result in 
the entire dataset being subjected to fitting.
- **`Center data`**: Checking this box leads to the centering of mood and 
external factor values for individual subjects.
- **`FIT`**: The application extracts and fits data for individual subjects 
iteratively. It will display the ID of the last successfully fitted subject 
along with the time taken. You will be prompted to save the results at the end. 

Following a successful fit, the following files are generated, with ID being 
replaced by the corresponding subject ID:

- **sbj_[ID].RData**: This file contains a "LARMExFit" R6 object named fit_[ID]. 
This object comprises various fields that can be accessed using the `$` 
notation. For instance, `fit_someID$rawData` gives access to the subject's data.
  * `rawData`: Data specific to the subject
  * `sjID`:    Variable name for subject ID
  * `nBeep`:   Variable name for the number of beeps
  * `nDay`:    Variable name for the number of days
  * `arList`:  List of interacting mood nodes
  * `exList`:  List of external factors influencing moods
  * `nAbb`:    Maximum length for abbreviating long names (not applicable if 0)
  * `arAbb`:   Abbreviated `arList`
  * `exAbb`:   Abbreviated `exlist` 
  * `fitID`:   Subject ID for fitting
  * `frm`:     Formula used for `lmer` fitting
  * `fitRes`:  Fitting results
  * `feM`:     Adjacency matrix for fixed effects
  * `reM`:     Adjacency matrix for random effects
  * `doCenter`: Indicates if mood and external factor values were centered per 
  subject
- **summary_[ID].txt**: This file contains the output of `lm4::summary()`
- **fe_[ID].csv**: This file includes fixed-effects estimates
- **re_[ID].csv**: This file provides random-effects estimates
